### ISSUE TITLE
Bug when there is not display installed on the server

### ISSUE THREAD

**Issue by lelouar** [ronin-gw/PyMaSC#12]
Traceback (most recent call last):
  File "/nfs/work/gen2i/technique/tools/bin/pymasc", line 33, in <module>
    sys.exit(load_entry_point('PyMaSC==0.3.2', 'console_scripts', 'pymasc')())
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/__init__.py", line 20, in _inner
    main_func()
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/pymasc.py", line 98, in main
    output_results(args, output_basename, result_handler)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/pymasc.py", line 201, in output_results
    plot_figures(plotfile_path, result_handler)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/utils/output.py", line 10, in _io_func
    return func(*args, **kwargs)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/output/figure.py", line 34, in plot_figures
    plot_naive_cc(ccr, name)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/PyMaSC/output/figure.py", line 92, in plot_naive_cc
    plt.title(title)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3108, in title
    return gca().set_title(
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2368, in gca
    return gcf().gca(**kwargs)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/pyplot.py", line 747, in gcf
    return figure()
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/pyplot.py", line 693, in figure
    **kwargs)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/nfs/work/gen2i/technique/tools/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "unix10.30.250.252:25.0"

is it possible to skip this when server has not X server installed ?

thx :)

**Comment by ronin-gw** [comment]
Yes, you can skip plotting with the `--skip-plots` option. And you can generate plots later by using the `pymasc-plot` command.

**Comment by lelouar** [comment]
thx :+1:
